### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by jarmitage** [ulyssesp/LambdaDesigner#3]
Would be good if this was broken down a bit more, starting from `stack install LambdaDesigner`

**Comment by ulyssesdotcodes** [comment]
Fixed with e5d5512498d4cbd8a8814615cb7e43da00145127. Does that cover all the issues you had?

**Comment by jarmitage** [comment]
Assuming that `stack build` installs `LambdaDesigner` then yes (I did `stack install LambdaDesigner` and then `stack install` in the directory because I was just guessing)
